### ISSUE TITLE
where is the source for https://cdn.worldiety.org/golang.org/gomobile-wdy-v0.0.2.zip

### ISSUE THREAD

**Issue by gedw99** [worldiety/goup#7]
just want to see what GOUP is installing....

**Comment by torbenschinke** [comment]
there was no build automation behind that. That started originally as a build script and evolved into this tool over time. I just zipped and threw that by hand into the zip files. It looks like that I have never tagged the first few versions. But most likely they came from this repo, like the other [tags](https://github.com/worldiety/goup/tags?after=v0.0.15).

**Comment by gedw99** [comment]
Thanks @torbenschinke 

makes sense and no need for further investigation
